apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Use the Let's Encrypt staging server first to avoid rate limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: marius.kiskemper@atos.net    # <-- replace with your email
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
